#ifndef		__LED_H
#define		__LED_H

#include "global.h"
#include "stdint.h"
#include "stm32f4xx.h"

#define BLUE_ON						HAL_GPIO_WritePin(LED_PORT,LED_BLUE,GPIO_PIN_SET);
#define BLUE_OFF					HAL_GPIO_WritePin(LED_PORT,LED_BLUE,GPIO_PIN_RESET);

#define RED_ON						HAL_GPIO_WritePin(LED_PORT,LED_RED,GPIO_PIN_SET);
#define RED_OFF						HAL_GPIO_WritePin(LED_PORT,LED_RED,GPIO_PIN_RESET);

#define GREEN_ON					HAL_GPIO_WritePin(LED_PORT,LED_GREEN,GPIO_PIN_SET);
#define GREEN_OFF					HAL_GPIO_WritePin(LED_PORT,LED_GREEN,GPIO_PIN_RESET);

#define YELLOW_ON					HAL_GPIO_WritePin(LED_PORT,LED_YELLOW,GPIO_PIN_SET);
#define YELLOW_OFF				HAL_GPIO_WritePin(LED_PORT,LED_YELLOW,GPIO_PIN_RESET);

#define WHITE_ON					HAL_GPIO_WritePin(LED_PORT,LED_WHITE,GPIO_PIN_SET);
#define WHITE_OFF					HAL_GPIO_WritePin(LED_PORT,LED_WHITE,GPIO_PIN_RESET);

#define LED_ALL_ON				HAL_GPIO_WritePin(LED_PORT,LED_WHITE|LED_YELLOW|LED_GREEN|LED_RED|LED_BLUE,GPIO_PIN_SET);
#define LED_ALL_OFF				HAL_GPIO_WritePin(LED_PORT,LED_WHITE|LED_YELLOW|LED_GREEN|LED_RED|LED_BLUE,GPIO_PIN_RESET);

#define LED_ON(PIN)					HAL_GPIO_WritePin(LED_PORT,PIN,GPIO_PIN_SET);
#define LED_OFF(PIN)				HAL_GPIO_WritePin(LED_PORT,PIN,GPIO_PIN_RESET);

extern uint8_t led_index;

void TurnLED(void);

#endif
